const enum LABEL {
  CAMILLE_PISSARRO = "camille_pissarro",
  EDGAR_DEGAS = "edgar_degas",
  EUGENE_BOUDIN = "eugene_boudin",
  EUGENE_DELACROIX = "eugene_delacroix",
  GEORGES_SEURAT = "georges_seurat",
  GILBERT_STUART = "gilbert_stuart",
  HENRI_DE_TOULOUSE_LAUTREC = "henri_de_toulouse_lautrec",
  HENRI_FANTIN_LATOUR = "henri_fantin_latour",
  IMPRESSIONIST = "impressionist",
  JAMES_MCNEILL_WHISTLER = "james_mcneill_whistler",
  JEAN_BAPTISTE_CAMILLE_COROT = "jean_baptiste_camille_corot",
  JEAN_FRANCOIS_MILLET = "jean_francois_millet",
  JESEPH_MALLORD_WILLIAM_TURNER = "jeseph_mallord_william_turner",
  JOHN_CONSTABLE = "john_constable",
  JOHN_SINGLETON_COPLEY = "john_singleton_copley",
  PAUL_CEZANNE = "paul_cezanne",
  PAUL_GAUGUIN = "paul_gauguin",
  POST_IMPRESSIONIST = "post_impressionist",
  REALIST = "realist",
  RICHARD_PARKES_BONINGTON = "richard_parkes_bonington",
  ROMANTIC = "romantic",
  SKETCH = "sketch",
  THEODORE_GERICAULT = "theodore_gericault",
  THEODORE_ROUSSEAU = "theodore_rousseau",
  THOMAS_SULLY = "thomas_sully",
  TONALISM = "tonalism",
  VINCENT_VAN_GOGH = "vincent_van_gogh",
}

const enum CATEGORY {
  IMPRESSIONIST = "인상주의",
  POST_IMPRESSIONIST = "후기인상주의",
  REALIST = "사실주의",
  ROMANTIC = "낭만주의",
  SKETCH = "스케치",
  TONALISM = "토날리즘",
}

const enum ARTIST {
  CAMILLE_PISSARRO = "카미유 피사로",
  EDGAR_DEGAS = "에드가 드가",
  EUGENE_BOUDIN = "외젠 부댕",
  EUGENE_DELACROIX = "외젠 들라크루아",
  GEORGES_SEURAT = "조르주 쇠라",
  GILBERT_STUART = "길버트 스튜어트",
  HENRI_DE_TOULOUSE_LAUTREC = "앙리 드 툴루즈로트레크",
  HENRI_FANTIN_LATOUR = "앙리 팡탱라투르",
  JAMES_MCNEILL_WHISTLER = "제임스 애벗 맥닐 휘슬러",
  JEAN_BAPTISTE_CAMILLE_COROT = "장바티스트 카미유 코로",
  JEAN_FRANCOIS_MILLET = "장프랑수아 밀레",
  JESEPH_MALLORD_WILLIAM_TURNER = "조지프 말로드 윌리엄 터너",
  JOHN_CONSTABLE = "존 컨스터블",
  JOHN_SINGLETON_COPLEY = "존 싱글턴 코플리",
  PAUL_CEZANNE = "폴 세잔",
  PAUL_GAUGUIN = "폴 고갱",
  RICHARD_PARKES_BONINGTON = "리처드 파크스 보닝턴",
  THEODORE_GERICAULT = "테오도르 제리코",
  THEODORE_ROUSSEAU = "테오도르 루소",
  THOMAS_SULLY = "토마스 설리",
  VINCENT_VAN_GOGH = "빈센트 반 고흐",
}

export { LABEL, CATEGORY, ARTIST };
