const FOLDER_NAME = {
  CAMILLE_PISSARRO: "camille_pissarro",
  EDGAR_DEGAS: "edgar_degas",
  EUGENE_BOUDIN: "eugene_boudin",
  EUGENE_DELACROIX: "eugene_delacroix",
  GEORGES_SEURAT: "georges_seurat",
  GILBERT_STUART: "gilbert_stuart",
  HENRI_DE_TOULOUSE_LAUTREC: "henri_de_toulouse_lautrec",
  HENRI_FANTIN_LATOUR: "henri_fantin_latour",
  IMPRESSIONIST: "impressionist",
  JAMES_MCNEILL_WHISTLER: "james_mcneill_whistler",
  JEAN_BAPTISTE_CAMILLE_COROT: "jean_baptiste_camille_corot",
  JEAN_FRANCOIS_MILLET: "jean_francois_millet",
  JESEPH_MALLORD_WILLIAM_TURNER: "jeseph_mallord_william_turner",
  JOHN_CONSTABLE: "john_constable",
  JOHN_SINGLETON_COPLEY: "john_singleton_copley",
  PAUL_CEZANNE: "paul_cezanne",
  PAUL_GAUGUIN: "paul_gauguin",
  POST_IMPRESSIONIST: "post_impressionist",
  REALIST: "realist",
  RICHARD_PARKES_BONINGTON: "richard_parkes_bonington",
  ROMANTIC: "romantic",
  SKETCH: "sketch",
  THEODORE_GERICAULT: "theodore_gericault",
  THEODORE_ROUSSEAU: "theodore_rousseau",
  THOMAS_SULLY: "thomas_sully",
  TONALISM: "tonalism",
  USER_IMAGES: "user_images",
  VINCENT_VAN_GOGH: "vincent_van_gogh",
};

export { FOLDER_NAME };
